<a href="https://colab.research.google.com/github/NinaMoisienko18/KSVD/blob/main/Moisienko_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1
  Посилання на GitHub:

1) Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
v = np.arange(1, 21)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

2) Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [ ]:
m = np.ones((4, 4), dtype=int)
m

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

3) Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [ ]:
np.random.uniform(-1, 1, size=(5,5))

array([[-0.5708428 ,  0.54082769,  0.71927914,  0.46158085,  0.72209933],
       [ 0.07226988,  0.54403327, -0.44827285,  0.49406789,  0.70983725],
       [ 0.48212008,  0.98887147, -0.79669715,  0.4144964 ,  0.6004116 ],
       [ 0.02982582,  0.75051538, -0.40498755, -0.18247813, -0.7650994 ],
       [ 0.51011967,  0.31714765, -0.43362934,  0.02861812,  0.37331157]])

4) Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
np.random.uniform(0, 1, size=(3,3))

array([[0.28901091, 0.75416948, 0.26113051],
       [0.1242609 , 0.27948813, 0.58557065],
       [0.2427204 , 0.24922014, 0.89577986]])

5) Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 21, size=(1,6))
b = np.random.randint(1, 21, size=(1,6))

print(f"a = {a} \nb = {b}\n")
print(f"a + b = {a+b}")
print(f"a - b = {a-b}")
print(f"a * b = {a*b}")

a = [[ 6 14 10  9 19 12]] 
b = [[ 8 18 17 13  8 19]]

a + b = [[14 32 27 22 27 31]]
a - b = [[-2 -4 -7 -4 11 -7]]
a * b = [[ 48 252 170 117 152 228]]


6) Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 6, size=(3,2))
b = np.random.randint(1, 6, size=(2,4))

a

array([[3, 4],
       [2, 3],
       [2, 4]])

In [ ]:
b

array([[2, 2, 5, 4],
       [3, 3, 3, 3]])

In [ ]:
print("a * b = ")
np.dot(a, b)

a * b = 


array([[18, 18, 27, 24],
       [13, 13, 19, 17],
       [16, 16, 22, 20]])

7) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
m = np.random.uniform(0, 1, size=(3,3))
print(m)
print()
print(m.transpose())

[[0.4185598  0.34550572 0.34711334]
 [0.00959018 0.72537396 0.63199739]
 [0.39793655 0.14794601 0.45978706]]

[[0.4185598  0.00959018 0.39793655]
 [0.34550572 0.72537396 0.14794601]
 [0.34711334 0.63199739 0.45978706]]


8) Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
a = np.random.randint(1, 11, size=(3,3))
b = np.random.randint(1, 11, size=(3,3))
a-b

array([[-7,  2, -4],
       [-7, -7,  3],
       [ 0,  1, -6]])

9) Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [ ]:
a = np.random.randint(-5, 5, size=(3,3))
b = np.random.randint(-5, 5, size=(3,3))

a

array([[ 2, -1,  3],
       [ 1, -4, -2],
       [ 2, -5, -4]])

In [ ]:
b

array([[-3,  3,  0],
       [-2,  2,  3],
       [ 0, -2, -3]])

In [ ]:
np.dot(a, b)

array([[ -4,  -2, -12],
       [  5,  -1,  -6],
       [  4,   4,  -3]])

10) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
m = np.random.uniform(-1, 1, size=(3,3))

m

array([[-0.17561103,  0.75435971, -0.14200905],
       [ 0.61818637, -0.91074466, -0.33901319],
       [-0.50726884,  0.62772903,  0.82276577]])

In [ ]:
m.sum(axis=0).reshape(3, 1)

array([[-0.0646935 ],
       [ 0.47134408],
       [ 0.34174353]])